export const APEX_INFINITY_AGENTS = [
  { id: 1, name: 'SEC 8-K Watcher', cost: '$0' },
  { id: 2, name: '10-K Risk Delta', cost: '$0' },
  { id: 3, name: 'Insider Trade Tracker', cost: '$0' },
  { id: 4, name: 'Earnings Call NLP', cost: '$0' },
  { id: 5, name: 'Management Language Decoder', cost: '$0' },
  { id: 6, name: 'Polymarket Base Rate', cost: '$0' },
  { id: 7, name: 'Polymarket Bayesian Updater', cost: '$0' },
  { id: 8, name: 'Order Book Imbalance', cost: '$0' },
  { id: 9, name: 'Resolution Criteria Lawyer', cost: '$0' },
  { id: 10, name: 'Time-Decay Arbitrageur', cost: '$0' },
  { id: 11, name: 'Pattern CNN', cost: '$0' },
  { id: 12, name: 'Multi-Timeframe Confluencer', cost: '$0' },
  { id: 13, name: 'Volume Microstructure', cost: '$0' },
  { id: 14, name: 'Job Posting Intel', cost: '$0' },
  { id: 15, name: 'Google Trends Predictor', cost: '$0' },
  { id: 16, name: 'App Store Sentiment', cost: '$0' },
  { id: 17, name: 'GitHub Commit Velocity', cost: '$0' },
  { id: 18, name: 'Reddit Crowd Contrarian', cost: '$0' },
  { id: 19, name: 'Dark Pool Options Flow', cost: '$0' },
  { id: 20, name: 'Activist Filing Alert', cost: '$0' },
  { id: 21, name: 'Macro Regime Detector', cost: '$0' },
  { id: 22, name: 'Intermarket Correlator', cost: '$0' },
  { id: 23, name: 'Supply Chain Monitor', cost: '$0' },
  { id: 24, name: 'Bayesian Probability Engine', cost: '$0' },
  { id: 25, name: 'Kelly Sizer', cost: '$0' },
  { id: 26, name: "Devil's Advocate ×3", cost: '$0' },
  { id: 27, name: 'Master Synthesizer', cost: '$0.01' },
] as const;
